-- Writes web/js/preview-world.js from config_world.lua so the browser preview shows the real activity list.
-- Run from the resource root: lua5.4 dev/export_world.lua   (dev/smoke.py checks it is up to date)
vec3 = function(x, y, z) return { x = x, y = y, z = z } end
dofile('config.lua'); dofile('config_world.lua')
local function q(s) return '"' .. tostring(s or ''):gsub('\\', '\\\\'):gsub('"', '\\"') .. '"' end
local out = { "'use strict';", '/* Generated by dev/export_world.lua from config_world.lua. Browser preview only; do not edit. */', 'const PREVIEW_WORLD = {' }
for _, h in ipairs(Config.Holidays) do
    local acts = Config.World[h.id]
    if acts then
        local items = {}
        for i, a in ipairs(acts) do
            local n = a.type == 'spots' and #(type(a.spots) == 'string' and Config.Places[a.spots] or a.spots) or nil
            items[#items + 1] = ('    { key: %s, type: %s, title: %s, desc: %s, icon: %s, cap: %d%s%s%s }'):format(q(a.key), q(a.type), q(a.title), q(a.desc), q(a.icon),
                a.perDay or 1, n and (', total: %d'):format(n) or '', a.at and (', at: %s'):format(q(a.at)) or '', a.timeLimit and (', timeLimit: %d'):format(a.timeLimit) or '')
        end
        out[#out + 1] = ('  %s: [\n%s,\n  ],'):format(h.id, table.concat(items, ',\n'))
    end
end
out[#out + 1] = '};'
local f = assert(io.open('web/js/preview-world.js', 'w')); f:write(table.concat(out, '\n') .. '\n'); f:close()
print('wrote web/js/preview-world.js')
