#!/usr/bin/env python3
"""Click-through smoke test of the NUI preview (mock server). Exits non-zero on any failure.
Setup once: pip install -r dev/requirements.txt && playwright install chromium"""
import sys
from pathlib import Path
from playwright.sync_api import sync_playwright

URL = (Path(__file__).resolve().parent.parent / 'web' / 'index.html').as_uri()
results, errors = [], []
def check(name, cond): results.append((name, bool(cond)))

with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(viewport={'width': 1920, 'height': 1080})
    pg.on('pageerror', lambda e: errors.append(str(e)))
    def go(q): pg.goto(URL + q); pg.wait_for_timeout(1800)

    go('?holiday=halloween')
    check('contest: sidebar shows the leaderboard', pg.inner_text('.list-card h2') == 'Leaderboard' and pg.locator('#upcoming.board li').count() == 6)
    check('contest: your row is pinned below the top 5', pg.locator('#upcoming.board li.you.gap').count() == 1)
    check('contest: countdown shows time left', pg.inner_text('#countdown').startswith('Ends in'))
    check('halloween: stat cards and city card render', pg.locator('#stats .stat').count() == 4 and pg.locator('#extra .city .meter').count() == 2)
    check('halloween: street is dark with a flashlight beam', pg.locator('.scene.lights-out .dark').count() == 1)
    pts0 = pg.evaluate('state.event.contest.points')
    pg.evaluate("window.__g = launchGhost(document.querySelector('.scene'))")
    for _ in range(40):  # keep the beam (cursor) on the drifting ghost until it is trapped
        if not pg.evaluate('document.body.contains(window.__g)'): break
        bb = pg.evaluate('(() => { const r = window.__g.getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; })()')
        pg.mouse.move(bb[0], bb[1]); pg.wait_for_timeout(70)
    pg.wait_for_timeout(300)
    check('halloween: holding the flashlight on a ghost traps it', pg.evaluate('state.event.ghost') is False and pg.evaluate('state.event.contest.points') > pts0)
    pg.mouse.click(5, 5); pg.wait_for_timeout(400)
    pg.click('.spot:not([disabled])'); pg.wait_for_timeout(400)
    check('halloween: opening a house increments used', pg.evaluate('state.event.used') == 3)
    check('contest: points from a play land on the board', pg.evaluate('state.event.contest.points') > 85)
    go('?holiday=halloween&closed')
    check('contest closed: podium with three places', pg.locator('.podium .pod').count() == 3 and pg.locator('.results .trophy').count() == 1)
    check('contest closed: claim button for a winner', pg.locator('.grace.ready[data-arg="8"]').count() == 1)
    pg.click('.grace.ready'); pg.wait_for_timeout(400)
    check('contest closed: claiming marks the prize claimed', pg.evaluate('state.event.contest.prize.claimed') is True and pg.locator('.grace.ready').count() == 0)
    go('?holiday=easter')
    check('sidebar resets to Coming up off-contest', pg.inner_text('.list-card h2') == 'Coming up' and pg.evaluate("document.getElementById('upcoming').className") == '')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    check('esc hides the UI', pg.evaluate("document.getElementById('app').classList.contains('hidden')"))
    check('timers stop when hidden', pg.evaluate('timers.length') == 0)
    for hid in ('presidents', 'mothers_day', 'fathers_day', 'columbus'):  # every pick-and-reveal holiday plays
        go(f'?holiday={hid}'); u0 = pg.evaluate('state.event.used'); pg.click('.spot:not([disabled])'); pg.wait_for_timeout(400)
        check(f'{hid}: a pick reveals a reward', pg.evaluate('state.event.used') == u0 + 1 and pg.locator('.reveal, .msg:not(:empty)').count() >= 1)
    go('?holiday=columbus&both')
    check('overlap: switcher lists both holidays, opens on the day-of one', pg.locator('#now .pick').count() == 2 and pg.evaluate('state.event.id') == 'columbus' and 'Halloween' not in pg.inner_text('#upcoming'))
    pg.click('#now .pick[data-sel=halloween]'); pg.wait_for_timeout(300)
    check('overlap: switching shows Halloween with its own theme and board', pg.evaluate('state.event.id') == 'halloween' and pg.inner_text('#title') == 'Halloween' and pg.inner_text('#now h2') == 'Happening now' and pg.inner_text('.list-card h2') == 'Leaderboard' and pg.locator('#upcoming.board').count() == 1)
    go('?holiday=easter')
    check('switcher hidden with one holiday', pg.locator('#now').is_hidden())
    go('?holiday=juneteenth'); pg.click('.plate.ready'); pg.wait_for_timeout(400)
    check('juneteenth: cookout dish grabbed', pg.evaluate('state.event.dishes[2].status') == 'served' and pg.locator('.cloth.gingham').count() == 1)
    go('?holiday=labor'); pg.click('.punch.ready'); pg.wait_for_timeout(400)
    check('labor: shift punched and stamped', pg.evaluate('state.event.dishes[3].status') == 'served' and pg.locator('.timecard .stamp').count() == 4)
    go('?holiday=mlk'); pg.click('.candle-btn.pledge'); pg.wait_for_timeout(400)
    check('mlk: pledge signed and counted', pg.evaluate('state.event.lit') is True and pg.evaluate('state.event.total') == 643)
    for hid in ('mlk', 'presidents', 'mothers_day', 'juneteenth', 'fathers_day', 'labor', 'columbus'):
        go(f'?holiday={hid}')
        check(f'{hid}: own art and stat cards', f'img/{hid}/' in pg.evaluate("document.getElementById('hero').style.backgroundImage") and pg.locator('#stats .stat').count() >= 2)
    go('?holiday=thanksgiving'); pg.click('.plate.ready'); pg.wait_for_timeout(400)
    check('feast: dish gets served', pg.evaluate('state.event.dishes[3].status') == 'served')
    go('?holiday=memorial'); pg.click('.candle-btn'); pg.wait_for_timeout(400)
    check('tribute: candle lit and total incremented', pg.evaluate('state.event.lit && state.event.total') == 1205)
    go('?holiday=new_years_eve'); pg.wait_for_timeout(600)
    check('countdown ticks', pg.inner_text('.clock b').count(':') == 2)
    go('?holiday=christmas&art'); pg.click('.door.ready'); pg.wait_for_timeout(400)
    check('advent: door claimed and reveal shown', pg.evaluate('state.advent.doors[11].status') == 'claimed' and pg.locator('.reveal').count() == 1)
    pg.click('#skin'); pg.wait_for_timeout(200)
    check('skin toggles to holo', pg.locator('.skin-holo').count() == 1)
    go('?admin')
    check('admin: tablet opens on the overview tab', pg.locator('.tablet .tab.on[data-tab=overview]').count() == 1 and pg.locator('.tiles .tile').count() == 4)
    pg.click('button[data-tab=holidays]'); pg.wait_for_timeout(150)
    pg.click('input[data-id=halloween][data-a=toggle]'); pg.wait_for_timeout(200)
    check('admin: toggle disables a holiday', pg.evaluate("ADM.holidays.find(h => h.id === 'halloween').enabled") is False)
    check('admin: tab survives a re-render', pg.locator('.tab.on[data-tab=holidays]').count() == 1)
    pg.click('button[data-tab=time]'); pg.wait_for_timeout(150)
    pg.fill('#adm-date', '2026-12-31'); pg.click('button[data-a=date]'); pg.wait_for_timeout(200)
    check('admin: date override reflected', 'overridden' in pg.inner_text('.adm header'))
    check('admin: ghost count in header', 'ghosts active' in pg.inner_text('.adm header'))
    pg.click('button[data-tab=halloween]'); pg.wait_for_timeout(150)
    pg.click('button[data-a=resetContest]'); pg.wait_for_timeout(100)
    check('admin: reset contest asks to confirm first', pg.inner_text('button[data-a=resetContest]') == 'Click again to confirm' and 'reset' not in pg.inner_text('.adm .note'))
    pg.click('button[data-a=resetContest]'); pg.wait_for_timeout(200)
    check('admin: reset contest runs on the second click', 'reset' in pg.inner_text('.adm .note'))
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    check('esc closes the admin panel first', pg.evaluate("adminEl.classList.contains('off')"))
    b.close()

for n, c in results: print(('PASS ' if c else 'FAIL ') + n)
print('page errors:', errors or 'none')
sys.exit(0 if all(c for _, c in results) and not errors else 1)
