#!/usr/bin/env python3
"""Click-through smoke test of the NUI preview (mock server). Exits non-zero on any failure.
Setup once: pip install -r dev/requirements.txt && playwright install chromium"""
import sys
from pathlib import Path
from playwright.sync_api import sync_playwright

URL = (Path(__file__).resolve().parent.parent / 'web' / 'index.html').as_uri()
ROOT = Path(__file__).resolve().parent.parent
results, errors = [], []
def check(name, cond): results.append((name, bool(cond)))

with sync_playwright() as p:
    b = p.chromium.launch(); pg = b.new_page(viewport={'width': 1920, 'height': 1080})
    pg.on('pageerror', lambda e: errors.append(str(e)))
    def go(q): pg.goto(URL + q); pg.wait_for_timeout(1800)

    # ---- City hub (default): every holiday lists its city activities ----
    IDS = ['christmas', 'halloween', 'valentines', 'easter', 'stpatricks', 'independence', 'thanksgiving', 'new_years_eve', 'new_years', 'memorial', 'labor']
    for hid in IDS:
        go(f'?holiday={hid}')
        n = pg.evaluate(f"(PREVIEW_WORLD['{hid}'] || []).length")
        check(f'hub {hid}: {n} city activities as cards with own art', n >= 1 and pg.locator('.act-grid .act[data-type=spots], .act-grid .act[data-type=delivery], .act-grid .act[data-type=gathering]').count() == n
              and f'img/{hid}/' in pg.evaluate("document.getElementById('hero').style.backgroundImage") and pg.locator('#stats .stat').count() >= 2)
    go('?holiday=independence')
    pg.click('.act .wp[data-key=pads]'); pg.wait_for_timeout(300)
    check('hub: set waypoint answers with a toast', 'Waypoint set' in pg.inner_text('#msg'))
    check('hub: gathering card counts down', pg.locator('.act[data-type=gathering] .cd').count() == 1 and 'h' in pg.inner_text('.act[data-type=gathering] .cd'))
    go('?holiday=valentines')
    check('hub: delivery in progress shows its timer', pg.locator('.act[data-type=delivery] .cd').count() == 1)
    go('?holiday=halloween')
    check('hub halloween: leaderboard, contest stats and ghost card', pg.inner_text('.list-card h2') == 'Leaderboard' and pg.locator('.act[data-type=ghosts]').count() == 1 and 'pts' in pg.inner_text('#stats'))
    go('?holiday=christmas&art')
    pg.click('.act[data-type=advent] .wp'); pg.wait_for_timeout(300)
    check('hub christmas: advent card opens the calendar with a way back', pg.locator('.door').count() == 24 and pg.locator('#back').is_visible())
    pg.click('.door.ready'); pg.wait_for_timeout(400)
    check('hub christmas: claim a door from the calendar', pg.evaluate('state.advent.doors[11].status') == 'claimed')
    pg.click('#back'); pg.wait_for_timeout(300)
    check('hub christmas: back returns to the city activities', pg.locator('.act-grid').count() == 1 and pg.locator('#back').is_hidden())
    go('?holiday=halloween&closed')
    check('hub: closed contest shows the podium and a claim button', pg.locator('.podium .pod').count() == 3 and pg.locator('.grace.ready[data-arg="8"]').count() == 1)
    pg.click('.grace.ready'); pg.wait_for_timeout(400)
    check('hub: claiming the prize marks it claimed', pg.evaluate('state.event.contest.prize.claimed') is True)
    go('?holiday=new_years_eve&both')
    check("hub overlap (Dec 31): switcher for New Year's Eve and New Year's Day", pg.locator('#now .pick').count() == 2 and pg.inner_text('#title') == "New Year's Eve")
    pg.click('#now .pick[data-sel=new_years]'); pg.wait_for_timeout(300)
    check("hub overlap: switching shows New Year's Day activities", pg.inner_text('#title') == "New Year's Day" and pg.locator('.act-grid .act').count() == 2)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    check('hub: esc hides the UI and stops the countdown timers', pg.evaluate("document.getElementById('app').classList.contains('hidden')") and pg.evaluate('timers.length') == 0)

    # ---- Legacy in-menu mini games (Config.MenuGames = true) ----
    go('?holiday=halloween&games')
    check('contest: sidebar shows the leaderboard', pg.inner_text('.list-card h2') == 'Leaderboard' and pg.locator('#upcoming.board li').count() == 6)
    check('contest: your row is pinned below the top 5', pg.locator('#upcoming.board li.you.gap').count() == 1)
    check('contest: countdown shows time left', pg.inner_text('#countdown').startswith('Ends in'))
    check('halloween: stat cards and city card render', pg.locator('#stats .stat').count() == 4 and pg.locator('#extra .city .meter').count() == 2)
    check('halloween: street is dark with a flashlight beam', pg.locator('.scene.lights-out .dark').count() == 1)
    pts0 = pg.evaluate('state.event.contest.points')
    pg.evaluate("window.__g = launchGhost(document.querySelector('.scene'))")
    for _ in range(40):  # keep the beam (cursor) on the drifting ghost until it is trapped
        if not pg.evaluate('document.body.contains(window.__g)'): break
        bb = pg.evaluate('(() => { const r = window.__g.getBoundingClientRect(); return [r.left + r.width / 2, r.top + r.height / 2]; })()')
        pg.mouse.move(bb[0], bb[1]); pg.wait_for_timeout(70)
    pg.wait_for_timeout(300)
    check('halloween: holding the flashlight on a ghost traps it', pg.evaluate('state.event.ghost') is False and pg.evaluate('state.event.contest.points') > pts0)
    pg.mouse.click(5, 5); pg.wait_for_timeout(400)
    pg.click('.spot:not([disabled])'); pg.wait_for_timeout(400)
    check('halloween: opening a house increments used', pg.evaluate('state.event.used') == 3)
    check('contest: points from a play land on the board', pg.evaluate('state.event.contest.points') > 85)
    go('?holiday=halloween&closed&games')
    check('contest closed: podium with three places', pg.locator('.podium .pod').count() == 3 and pg.locator('.results .trophy').count() == 1)
    check('contest closed: claim button for a winner', pg.locator('.grace.ready[data-arg="8"]').count() == 1)
    pg.click('.grace.ready'); pg.wait_for_timeout(400)
    check('contest closed: claiming marks the prize claimed', pg.evaluate('state.event.contest.prize.claimed') is True and pg.locator('.grace.ready').count() == 0)
    go('?holiday=easter&games')
    check('sidebar resets to Coming up off-contest', pg.inner_text('.list-card h2') == 'Coming up' and pg.evaluate("document.getElementById('upcoming').className") == '')
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    check('esc hides the UI', pg.evaluate("document.getElementById('app').classList.contains('hidden')"))
    check('timers stop when hidden', pg.evaluate('timers.length') == 0)
    go('?holiday=valentines&games'); u0 = pg.evaluate('state.event.used'); pg.click('.spot:not([disabled])'); pg.wait_for_timeout(400)
    check('valentines: a pick reveals a reward', pg.evaluate('state.event.used') == u0 + 1)
    go('?holiday=new_years_eve&both&games')
    check('overlap: switcher lists both holidays, opens on the day-of one', pg.locator('#now .pick').count() == 2 and pg.evaluate('state.event.id') == 'new_years_eve' and "New Year's Day" not in pg.inner_text('#upcoming'))
    pg.click('#now .pick[data-sel=new_years]'); pg.wait_for_timeout(300)
    check("overlap: switching shows New Year's Day with its own game", pg.evaluate('state.event.id') == 'new_years' and pg.inner_text('#title') == "New Year's Day" and pg.inner_text('#now h2') == 'Happening now' and pg.locator('.spot').count() == 3)
    go('?holiday=easter&games')
    check('switcher hidden with one holiday', pg.locator('#now').is_hidden())
    go('?holiday=labor&games'); pg.click('.punch.ready'); pg.wait_for_timeout(400)
    check('labor: shift punched and stamped', pg.evaluate('state.event.dishes[3].status') == 'served' and pg.locator('.timecard .stamp').count() == 4)
    go('?holiday=thanksgiving&games'); pg.click('.plate.ready'); pg.wait_for_timeout(400)
    check('feast: dish gets served', pg.evaluate('state.event.dishes[3].status') == 'served')
    go('?holiday=memorial&games'); pg.click('.candle-btn'); pg.wait_for_timeout(400)
    check('tribute: candle lit and total incremented', pg.evaluate('state.event.lit && state.event.total') == 1205)
    go('?holiday=new_years_eve&games'); pg.wait_for_timeout(600)
    check('countdown ticks', pg.inner_text('.clock b').count(':') == 2)
    go('?holiday=christmas&art&games'); pg.click('.door.ready'); pg.wait_for_timeout(400)
    check('advent: door claimed and reveal shown', pg.evaluate('state.advent.doors[11].status') == 'claimed' and pg.locator('.reveal').count() == 1)
    pg.click('#skin'); pg.wait_for_timeout(200)
    check('skin toggles to holo', pg.locator('.skin-holo').count() == 1)
    go('?admin')
    check('admin: tablet opens on the overview tab', pg.locator('.tablet .tab.on[data-tab=overview]').count() == 1 and pg.locator('.tiles .tile').count() == 4)
    pg.click('button[data-tab=holidays]'); pg.wait_for_timeout(150)
    pg.click('input[data-id=halloween][data-a=toggle]'); pg.wait_for_timeout(200)
    check('admin: toggle disables a holiday', pg.evaluate("ADM.holidays.find(h => h.id === 'halloween').enabled") is False)
    check('admin: tab survives a re-render', pg.locator('.tab.on[data-tab=holidays]').count() == 1)
    pg.click('button[data-tab=time]'); pg.wait_for_timeout(150)
    pg.fill('#adm-date', '2026-12-31'); pg.click('button[data-a=date]'); pg.wait_for_timeout(200)
    check('admin: date override reflected', 'overridden' in pg.inner_text('.adm header'))
    check('admin: ghost count in header', 'ghosts active' in pg.inner_text('.adm header'))
    pg.click('button[data-tab=city]'); pg.wait_for_timeout(150)
    check('admin: city tab lists every holiday with its activities', pg.locator('.cityh').count() == 11 and pg.locator('.cityh button[data-a=tp]').count() == pg.evaluate('Object.values(PREVIEW_WORLD).flat().length'))
    pg.click('.cityh button[data-a=tp]'); pg.wait_for_timeout(200)
    check('admin: go there teleports', 'Teleported' in pg.inner_text('.adm .note'))
    pg.click('button[data-tab=halloween]'); pg.wait_for_timeout(150)
    pg.click('button[data-a=resetContest]'); pg.wait_for_timeout(100)
    check('admin: reset contest asks to confirm first', pg.inner_text('button[data-a=resetContest]') == 'Click again to confirm' and 'reset' not in pg.inner_text('.adm .note'))
    pg.click('button[data-a=resetContest]'); pg.wait_for_timeout(200)
    check('admin: reset contest runs on the second click', 'reset' in pg.inner_text('.adm .note'))
    pg.keyboard.press('Escape'); pg.wait_for_timeout(200)
    check('esc closes the admin panel first', pg.evaluate("adminEl.classList.contains('off')"))
    b.close()

# The preview's activity list is generated from config_world.lua; make sure nobody forgot to regenerate it
import shutil, subprocess
if shutil.which('lua5.4'):
    before = (ROOT / 'web/js/preview-world.js').read_text()
    subprocess.run(['lua5.4', 'dev/export_world.lua'], cwd=ROOT, check=True, capture_output=True)
    check('preview-world.js matches config_world.lua (run lua5.4 dev/export_world.lua)', (ROOT / 'web/js/preview-world.js').read_text() == before)

for n, c in results: print(('PASS ' if c else 'FAIL ') + n)
print('page errors:', errors or 'none')
sys.exit(0 if all(c for _, c in results) and not errors else 1)
